- title: Software / System Architecture
  desc: Lorem ipsum dolor sit amet, augue lacus duis aliquam interdum morbi, justo sequi eget nulla nec, dignissim
  icon: assets/images/services-icon-brush.png

- title: Custom Software Development
  desc: Lorem ipsum dolor sit amet, augue lacus duis aliquam interdum morbi, justo sequi eget nulla nec, dignissim
  icon: assets/images/services-icon-brush.png

- title: API Development / Integration
  desc: Lorem ipsum dolor sit amet, augue lacus duis aliquam interdum morbi, justo sequi eget nulla nec, dignissim
  icon: assets/images/services-icon-brush.png

- title: Team Development and Management
  desc: Lorem ipsum dolor sit amet, augue lacus duis aliquam interdum morbi, justo sequi eget nulla nec, dignissim
  icon: assets/images/services-icon-brush.png