- title: Multi-Tenancy with Keycloak
  desc: Implement multi-tenancy with Keycloak to address your enterprise needs.
  icon: assets/images/services-icon-pen.png

- title: Software / System Architecture
  desc: Defining the principle, standards and road-map to guide the development, operation and management of the software and technology.
  icon: assets/images/services-icon-coding.png

- title: Custom Software Development
  desc: Full-cycle software development leveraging the Java/Spring technology stack.
  icon: assets/images/services-icon-java.png

- title: API Development / Integration
  desc: Cut down development time and costs by integrating readily available third-party API platforms.
  icon: assets/images/services-icon-layer.png

- title: Team Development and Management
  desc: Recruit and retain local talents from the Philippines
  icon: assets/images/services-icon-brush.png
